[apt]
packages = ["python3-dev"]

[brew]
packages = ["ffmpeg"]

[node_reqs]
ComfyUI-VideoHelperSuite = "Kosinkadink/ComfyUI-VideoHelperSuite"
ComfyUI-CameraPack = "PozzettiAndrea/ComfyUI-CameraPack"
ComfyUI-HyMotion = "Aero-Ex/ComfyUI-HyMotion"