[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]
publish = true

[test.workflows]
timeout = 300
cpu = ["smpl_to_bvh_pipeline", "load_camera_traj", "apply_motion_on_character"]
gpu = ["GVHMR", "GVHMR_cameramotion"]

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true
linux_gpu = true
windows_gpu = true
windows_portable_gpu = true
