[project]
name = "ComfyUI-MotionCapture"
description = "Motion Capture nodes for ComfyUI: SMPL data/retargeting using GVHMR"
version = "0.0.5"
license = {file = "LICENSE"}

[tool.comfy]
PublisherId = "pznodes"
DisplayName = "MotionCapture"
Icon = ""
