[project]
name = "ComfyUI-MotionCapture"
description = "Motion Capture nodes for ComfyUI: SMPL data/retargeting using GVHMR"
version = "0.1.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/PozzettiAndrea/ComfyUI-MotionCapture"

[tool.comfy]
PublisherId = "pznodes"
DisplayName = "MotionCapture"
Icon = ""
