python = "3.11"

[apt]
packages = ["python3-dev"]

[cuda]
packages = ["dpvo-cuda", "torch-scatter", "torch", "torchvision"]

[pypi-dependencies]
numpy = ">=1.23.0,<2.0.0"
pillow = ">=9.0.0"
opencv-python-headless = ">=4.8.0"
scipy = "*"
lightning = ">=2.0.0"
hydra-core = ">=1.3.0"
hydra-zen = "*"
hydra-colorlog = "*"
timm = ">=0.9.0"
einops = ">=0.6.0"
rich = ">=13.0.0"
termcolor = "*"
joblib = ">=1.2.0"
scikit-image = ">=0.19.0"
imageio = ">=2.34.0"
av = ">=13.0.0"
ffmpeg-python = ">=0.2.0"
trimesh = ">=3.20.0"
chumpy-fork = "*"
smplx = ">=0.1.28"
pycolmap = "*"
bvh = ">=0.3"
cython_bbox = "*"
lapx = "*"
setuptools = ">=68.0"
yacs = ">=0.1.8"
huggingface-hub = ">=1.0.0"
gdown = ">=4.7.0"
roma = ">=1.3.0"
dill = ">=0.3.6"
fvcore = ">=0.1.5"
transformers = ">=4.50.0"
hf_xet = "*"
braceexpand = "*"
webdataset = ">=0.2.0"
loguru = ">=0.7.0"
optree = ">=0.9.0"
pyrootutils = ">=1.0.4"
iopath = ">=0.1.7"
tabulate = "*"
portalocker = "*"
comfy-3d-viewers = ">=0.1.0"
bpy = "==4.2"

[target.linux-64.pypi-dependencies]
pyrender = ">=0.1.45"
